cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl -y
  - if not exist "%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe" choco install googlechrome -y
  - choco upgrade googlechrome -y
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PROGRAMFILES(x86)%\Google\Chrome\Application;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - cpanm --quiet --installdeps --with-develop --notest .

build_script:
  - perl Build.PL
    
test_script:
  - prove -lr