language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
env:
  global:
    - TMPDIR=/tmp
before_install:
  - sudo apt-get install -y google-chrome
install:
  - cpanm -n EV IO::Socket::Socks IO::Socket::SSL Net::DNS::Native Role::Tiny Test::Pod Test::Pod::Coverage
  - cpanm -n --installdeps .
sudo: false
notifications:
  email: false